name: ju-baseline2
model_config:
  r: 4
  k: 20
  dilations:
  - 1
  - 2
  channels: 24
  conv: edge
  use_refiner: false
  upsampler: nodeshuffle
  hierarchical: false
  use_bottleneck: true
  use_global: true
train_config:
  batch_size: 8
  epochs: 10
  optimizer: adam
  lr: 0.001
  betas:
  - 0.9
  - 0.999
  save_every: 5
  augment: true
  loss_fn: cd
data_config:
  path: ../data/PU1K/train/pu1k_poisson_256_poisson_1024_pc_2500_patch50_addpugan.h5
  num_point: 256
  skip_rate: 1
  use_randominput: true
  rng_seed: 42
